### ISSUE TITLE
FindByCompanyID: json: cannot unmarshal number -62169984561 into Go value of type int32

### ISSUE THREAD

**Issue by bfontaine** [intercom/intercom-go#19]
Hello,

When I request the company using the API the JSON field `remote_created_at` is negative:

```json
{
  "type": "company",
  "remote_created_at": -62169984561
}
```

(I removed the other fields)

This causes `ic.Companies.FindByCompanyID` to fail with the following message: `json: cannot unmarshal number -62169984561 into Go value of type int32`.

**Comment by josler** [comment]
Fixed this in a general case in v2 as it stands, thanks.
