### ISSUE TITLE
Message.Save() fails to unmarshal template in API response

### ISSUE THREAD

**Issue by hilljgo** [intercom/intercom-go#54]
## Version info
  - intercom-go version: v2
  - Go version: 1.7

## Expected behavior
Create NewEmailMessage:
```Go
msg := intercom.NewEmailMessage(intercom.PERSONAL_TEMPLATE, intercom.Admin{ID: "111111"}, intercom.User{Email: "bob@abc.ca"}, "subject", "body")
```

Save response message from api:
```Go
savedMessage, err := newClient.Messages.Save(&msg)
if err != nil {
	return err
}
```
Then success!

#### 1. Create NewEmailMessage:
```Go
msg := intercom.NewEmailMessage(intercom.PERSONAL_TEMPLATE, intercom.Admin{ID: "111111"}, intercom.User{Email: "bob@abc.ca"}, "subject", "body")
```

#### 2. Save response message from api:
```Go
savedMessage, err := newClient.Messages.Save(&msg)
if err != nil {
	return err
}
```

#### 3. The email is successfully sent, but a json err is also returned:
`json: cannot unmarshal string into Go value of type intercom.MessageTemplate`

#### 1. Create new intercom client:
```Go
newClient := intercom.NewClient("xxxxxx", "xxxxxxxx...")
```

#### 2. Create new email message:
```Go
msg := intercom.NewEmailMessage(intercom.PERSONAL_TEMPLATE, intercom.Admin{ID: "111111"}, intercom.User{Email: "bob@abc.ca"}, "subject", "body")
```

#### 3. Save the message:
```Go
savedMessage, err := newClient.Messages.Save(&msg)
if err != nil {
    fmt.Printf("ERR: %+v\n", err)
    return err
}
```

##### 4. Observe json error being returned (but email still being sent):
```
"ERR: json: cannot unmarshal string into Go value of type intercom.MessageTemplate"
```

## Reason(?): api is returning the following json:
```json
{
    "type":"admin_message",
    "id":"1111111",
    "created_at":1473727877,
    "subject":"subject",
    "body":"body",
    "template":"personal",
    "message_type":"email",
    "owner":{
        "type":"admin",
        "id":"1111111",
        "name":"John Doe",
        "email":"bob@abc.ca"
    }
}
```

[Line 25](https://github.com/intercom/intercom-go/blob/95c8070886f9e0833ec6200fa19c45b43a7f131c/message_api.go#L25) in message_api.go is trying to unmarshal the response into a MessageResponse type, which has a field for 'Template' that is of type `MessageTemplate` which is an alias for `int`, but the api is returning the template as a string.

**Comment by mmartinic** [comment]
Hi @hilljgo, thanks for reporting this. It should be fixed now.
