### ISSUE TITLE
The conversation.markread method should be a PATCH/PUT request

### ISSUE THREAD

**Issue by theandrewykim** [intercom/intercom-go#59]
Maybe I'm missing something but our API Docs say the mark read method is a PUT request. I've used PATCH when submitting postman requests and its worked, but it looks like the method in this SDK is a POST request.

```
func (api ConversationAPI) read(id string) (Conversation, error) {
	conversation := Conversation{}
	data, err := api.httpClient.Post(fmt.Sprintf("/conversations/%s", id), conversationReadRequest{Read: true})
	if err != nil {
		return conversation, err
	}
	err = json.Unmarshal(data, &conversation)
	return conversation, err
```

## Version info
  - intercom-go version: v2

**Comment by choran** [comment]
Hi @theandrewykim,
I tried to POST in the API and it fails but the PUT works. Same with the MarkRead method here:
"404: not_found, The requested resource does not exist; check your path and try again"
I was just checkin to see if you were able to confirm that this was failing for you too or whether you were able to get it working?
Cheers
Cathal

**Comment by choran** [comment]
Hi @theandrewykim 
I was just checking to see if you had an update here?
I will close this for now but please re-open if you are still having an issue
Thanks
Cathal
