### ISSUE TITLE
Add Scroll API

### ISSUE THREAD

**Issue by calvinfo** [intercom/intercom-go#66]
## Version info
  - intercom-go version: latest
  - Go version: 1.8

## Expected behavior

We'd love to see support for the Intercom Scroll API within this library. Right now it only supports listing users, but we'd love to see the ability to use the Scroll API with both users and contacts for large datasets.

https://developers.intercom.com/reference#iterating-over-all-users

## Actual behavior

N/A

## Steps to reproduce

N/A

## Logs

N/A

**Comment by choran** [comment]
Hi @calvinfo 
Scroll should now be available for users, leads and companies.
Please re-open if you have any issues getting this working.
Thanks
Cathal
