### ISSUE TITLE
appengine: urlfetch.Client not supported

### ISSUE THREAD

**Issue by mish15** [intercom/intercom-go#69]
## Version info
  - intercom-go version: 2
  - Go version: 1.7

## Expected behavior
A build tag would use the urlfetch.Client instead of the http.Client in `interfaces/http_client.go` if the code is being used on appengine. Or the client should support: 

```go
client.Option(intercom.SetHTTPClient(urlfetch.Client(ctx)))
```

## Actual behavior
appengine is not supported via build tags. Additionally the `HTTPClient` interface has an extra `Delete(string, interface{}) ([]byte, error)` method which prevents the urlfetch client from being used.

## Steps to reproduce
 1. use appengine

## Logs
```
cannot use "google.golang.org/appengine/urlfetch".Client(ctx) (type *http.Client) as type interfaces.HTTPClient in argument to intercom.SetHTTPClient:
	*http.Client does not implement interfaces.HTTPClient (missing Delete method)
```

**Comment by dhowden** [comment]
For reference, we have a work around for this issue (though it's a bit messy!):
```golang
client := intercom.NewClient(...)
httpClient, _ := client.HTTPClient.(interfaces.IntercomHTTPClient) // full error handling omitted for brevity
httpClient.Client = urlfetch.Client(ctx)
client.Option(intercom.SetHTTPClient(httpClient))
```

**Comment by choran** [comment]
HI @mish15 
Did the above workaround resolve your issue or are you still experiencing issue with this?
Thanks
Cathal

**Comment by mish15** [comment]
@choran we forked it from memory. So likely still an issue, but not for us currently.

**Comment by choran** [comment]
@mish15 thanks for the update.
For now I will close this as there appears to be a workaround. 
However, happy to re-open if people feel this is still and issue that needs to be addressed or updated.
