### ISSUE TITLE
Conversation does not include Tag List

### ISSUE THREAD

**Issue by jskrepnek** [intercom/intercom-go#76]
## Version info
  - intercom-go version: v2
  - Go version: 1.7

## Expected behavior
Conversations.Find should return a struct of a Conversation containing a tag.list.  The model returned from a method like Conversations.ListAll is slightly different in that it doesn't contain a tag.list, however the same struct is used for both methods.  The API *does* return a tag.list when calling 'Get a single conversation'

## Actual behavior
tag.list is not unmarshalled into the [Conversation](https://github.com/intercom/intercom-go/blob/v2/conversation.go#L15) returned by Conversations.Find.

Thanks for your work on the SDK.

**Comment by jskrepnek** [comment]
fixes intercom/intercom-go/issues/76

**Comment by choran** [comment]
Hi @jskrepnek 
Thanks for submitting the PR and sorry we have not got to it yet. We should be able to get to it this week. 
Cheers
Cathal

**Comment by choran** [comment]
Just closing this since the PR was merged
Thanks
Cathal
