### ISSUE TITLE
Setting avatar does not work (missing type)

### ISSUE THREAD

**Issue by Scorpiion** [intercom/intercom-go#80]
The Avatar object must have a type to be accepted by the API, this client does not have a type on the avatar object so it can't be set. 

See Avatar object description here:
https://developers.intercom.com/reference#section-avatar-object

See dotnet and java references here that has the type field:
- [dotnet](https://github.com/intercom/intercom-dotnet/blob/39bbf39c0f3e618cffd0daa46ea543ee5be3817f/src/Intercom/Data/Avatar.cs)
- [java](https://github.com/intercom/intercom-java/blob/master/intercom-java/src/main/java/io/intercom/api/Avatar.java)

I will make pull request for this now.

**Comment by choran** [comment]
Hi @Scorpiion 
Thanks for this, I was trying to test it but didnt manage to get it working.
Were you able to add the avatar using your changes?
If you were can you add a code example here in case I am testing it incorrectly ?
Thanks again
Cathal

**Comment by Scorpiion** [comment]
Hi @choran, sorry for not replying, been very busy. 

No I have not tested it, not sure if there are any other issues but as you concluded in the pull request this change makes sense either way. I will try this later again when I have more time. Thanks for the help.
