### ISSUE TITLE
Are "Contacts" the same as "Leads"

### ISSUE THREAD

**Issue by zwass** [intercom/intercom-go#90]
The API docs mention "Leads" but nothing about "Contacts". This repo doesn't mention anything about "Leads", but does have "Contacts". I'm assuming these are the same thing? Can this naming be fixed? Perhaps the old methods can be aliased so that it doesn't break backwards compatibility.

**Comment by choran** [comment]
Hi @zwass 
Yes, this is a good callout, they are the same but the API endpoint is still called contacts so that is something we need to address. For now I will make sure to add a note in the readme to clarify that contact and leads are the same thing.

**Comment by choran** [comment]
closing this as I updated the readme with clarification
